name: Destroy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy' # Simulating Environments feature
        required: true
        type: choice
        options:
          - sandbox
          - production

env:
  AWS_REGION: 'ap-southeast-2'
  AWS_ACCOUNT_ID: '123456789012'

jobs:
  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
  
    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v3

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve